Repository cybercongress/congress, pull requests merged in 2018-06, with the labels that each got.

#79 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs, bug, enhancement, in progress

#81 Create BUG and FEATURE issue templates
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/feature-request-issue-template.md
Labels: in progress

#80 UPD CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Docs, bug, in progress

#83 Add sprint 12 changelog
  Reports/Sprint12.md
Labels: in progress

#77 Update pipeline.md
  pipeline.md
Labels: in progress

#85 Add github project managment doc with rules
  Processes/github_project_management.md
Labels: in progress
